import { InputParameters, LogicConfig } from './types';

export const DEFAULT_LOGIC: LogicConfig = {
  version: 'v5.16.0',
  methanolCrackCoeff: 1.67, 
  nmConversionCoeff: 2.77, 
  ventilationCoeff: 1.3, // 默认值设置为1.3
  rxEfficiency: 5.3,
  n2Ratio: 1.1,
  methanolDensity: 0.8,
  elecPerLMethanol: 0.7,
  ln2ToGasCoeff: 647
};

export const DEFAULT_INPUTS: InputParameters = {
  projectName: 'PMRX100 100m3/h 吸热型气体发生器对比分析',
  customerName: '',
  runningDays: 300,
  runningHours: 24,
  naturalGasPrice: 3.95, 
  methanolPricePerTon: 3450, 
  nitrogenPricePerTon: 0.7, 
  electricityPrice: 0.86, 
  mode: 'nitrogen-methanol',
  methanolInputMode: 'liter-hour',
  methanolHourlyLiters: 35, // 默认值更新为 35
  currentMethanolAnnualTons: 201.6, // 默认值更新为 201.6
  currentNitrogenAnnualLiquidM3: 16.5, 
  rxHeatingType: 'gas',
  rxHeatingGasHourly: 1.5, // 默认值更新为 1.5
  rxHeatingElectricityHourly: 12, 
  rxElectricityHourly: 4.5, 
  investmentItems: [
    { model: 'PMRX100', quantity: 1, unitPrice: 0 }
  ],
  depreciationLife: 10,
  includeDepreciation: false,
};

export const EQUIPMENT_MODELS = [
  'PMRX50', 'PMRX50D', 'PMRX100', 'PMRX100D', 'PMRX200', 'PMRX200D', 'PMRX300', 'PMRX300D'
];

export const TRANSLATIONS = {
  zh: {
    company: "上海宝华威热处理设备有限公司",
    subtitleNM: "氮甲醇 + 氮气 VS Rx 发生气成本对比",
    subtitlePM: "纯甲醇 VS Rx 发生气成本对比",
    exportBtn: "PDF报告",
    projInfo: "项目基本信息",
    projName: "项目名称",
    custName: "客户名称",
    custPlaceholder: "在此输入客户单位名称...",
    basicData: "项目基础数据",
    currentSystem: "现状系统用量",
    rxSystem: "Rx 发生气方案 (B)",
    investmentSection: "设备投资",
    currency: "¥",
    currencyName: "RMB",
    weightUnit: "吨",
    volUnit: "立方",
    daysPerYear: "每年生产天数",
    hoursPerDay: "每天生产小时",
    ngPrice: "天然气单价 (元/m³)",
    methPrice: "甲醇单价 (元/吨)",
    n2Price: "单价 (元/m³)",
    elecPrice: "电力单价 (元/kWh)",
    methUsage: "甲醇年用量 (吨/年)",
    methHourly: "甲醇小时用量 (L/h)",
    n2UsageText: "液氮",
    n2HourlyText: "氮气",
    n2UsageUnit: "年用量 (m³/年)",
    n2HourlyUnit: "小时量 (m³/h)",
    n2WeightTooltip: "液氮重量为",
    modeSelect: "切换介质",
    modeNM: "氮甲醇",
    modePM: "纯甲醇",
    inputMode: "输入模式",
    inputModeT: "吨/年",
    inputModeL: "升/小时",
    heatingType: "加热方式",
    heatingGas: "加热用气 (m³/h)",
    heatingElec: "加热用电 (kWh/h)",
    rxElec: "运行功耗 (kWh/h)",
    gasHeating: "燃气加热",
    elecHeating: "电加热",
    totalPrice: "设备总价 (元)",
    depreciation: "折旧年限 (年)",
    calcDepr: "计入设备折旧",
    deprStatusIn: "已计入",
    deprStatusOut: "未计入",
    totalGas: "保护气总量",
    hourlyGas: "切换Rx气需求量",
    processNG: "天然气耗量",
    annualCost: "年度总成本",
    annualCostCurrent: "现状年度总成本",
    annualCostRx: "Rx 方案年度总成本",
    details: "详细费用对比",
    hourlyCost: "小时成本",
    savings: "年预计节省",
    savingsRate: "成本节约率",
    payback: "投资回收期",
    months: "个月",
    item: "费用项目",
    current: "现状系统",
    rx: "Rx 方案",
    diff: "差异",
    summary: "评估结论",
    signature: "工程师签字",
    approved: "审核确认",
    chartCostScale: "年度成本对比 (RMB)",
    fuelCost: "生产介质成本",
    auxCost: "辅助动力成本",
    maintDepr: "折旧成本",
    setupTitle: "PMRX系列气体发生器成本核算",
    supportText: "支持氮甲醇/纯甲醇方案与高效RX发生气方案的精准成本核算及ROI评估。",
    totalInvSummary: "设备投资总额",
    comparison: "对照",
    startBtn: "开始对比分析",
    backBtn: "返回修改",
    model: "型号",
    quantity: "数量",
    unitPrice: "单价",
    addItem: "添加设备",
    qty: "数量",
    calcPrinciple: "计算原理",
    viewDetail: "查看详细公式过程",
    summaryPriceTitle: "甲醇 / 氮气 / 天然气 / 电力单价",
    sourceBtn: "计算逻辑与源代码参数库",
    logicTitle: "换算逻辑与源代码参数库",
    logicSub: "核心引擎配置",
    physConst: "核心物理换算常数",
    methVapor: "甲醇蒸汽体积 (m³/L)",
    methDensity: "甲醇密度 (kg/L)",
    modeCoeff: "模式逻辑控制系数",
    nmCoeffTitle: "氮甲醇换算逻辑",
    nmCoeffHint: "产气量 = (甲醇 × 蒸汽系数) + 氮气; 氮气量 = (甲醇 × 蒸汽系数) × 4 / 6",
    pmCoeffTitle: "纯甲醇换气效率系数",
    pmCoeffHint: "产气量 = 甲醇 × 蒸汽系数 × 系数",
    rxRatioTitle: "Rx气与原料气比例",
    crackElecTitle: "裂解电耗 (kWh/L)",
    saveBtn: "保存并更新版本号",
    deprCost: "设备折旧费用",
    breakdownMethanol: "甲醇成本",
    breakdownNitrogen: "氮气/液氮成本",
    breakdownElec: "电力成本",
    breakdownGas: "天然气成本",
    ln2Coeff: "液氮汽化膨胀比 (倍)"
  },
  en: {
    company: "Shanghai PowerMax Furnace Corp.",
    subtitleNM: "N2-Methanol VS RX Gas Cost Analysis",
    subtitlePM: "Pure Methanol VS RX Gas Cost Analysis",
    exportBtn: "Export PDF",
    projInfo: "Project Information",
    projName: "Project Name",
    custName: "Customer Name",
    custPlaceholder: "Enter customer unit name...",
    basicData: "Basic Production Data",
    currentSystem: "Current Usage",
    rxSystem: "RX Gas Solution (B)",
    investmentSection: "Investment",
    currency: "$",
    currencyName: "USD",
    weightUnit: "Ton",
    volUnit: "m³",
    daysPerYear: "Running Days/Year",
    hoursPerDay: "Running Hours/Day",
    ngPrice: "NG Price ($/m³)",
    methPrice: "Methanol Price ($/T)",
    n2Price: "N2/LN2 Price ($/m³)",
    elecPrice: "Power Price ($/kW)",
    methUsage: "Methanol Annual (T/y)",
    methHourly: "Methanol Hourly (L/h)",
    n2UsageText: "LN2",
    n2HourlyText: "Nitrogen",
    n2UsageUnit: "Annual (m³/y)",
    n2HourlyUnit: "Hourly (m³/h)",
    n2WeightTooltip: "LN2 Weight is",
    modeSelect: "Medium",
    modeNM: "N2-Methanol",
    modePM: "Pure Methanol",
    inputMode: "Input Mode",
    inputModeT: "Ton/Year",
    inputModeL: "Liter/Hour",
    heatingType: "Heating",
    heatingGas: "Heating Gas (m³/h)",
    heatingElec: "Heating Power (kWh/h)",
    rxElec: "Op Power (kWh/h)",
    gasHeating: "Gas",
    elecHeating: "Electric",
    totalPrice: "Total Price",
    depreciation: "Depreciation (Y)",
    calcDepr: "Incl. Asset Depreciation",
    deprStatusIn: "Included",
    deprStatusOut: "Excluded",
    totalGas: "Total Gas Vol",
    hourlyGas: "Switching RX Gas Req",
    processNG: "NG Consumption",
    annualCost: "Annual Cost",
    annualCostCurrent: "Annual Cost (Current)",
    annualCostRx: "Annual Cost (RX)",
    details: "Detailed Cost Comparison",
    hourlyCost: "Cost/Hour",
    savings: "Annual Savings",
    savingsRate: "Savings Rate",
    payback: "Payback Period",
    months: "months",
    item: "Expense Item",
    current: "Current System",
    rx: "RX Solution",
    diff: "Diff",
    summary: "Evaluation Summary",
    signature: "Engineer Sign",
    approved: "Approved By",
    chartCostScale: "Annual Cost Comparison (USD)",
    fuelCost: "Production Medium Cost",
    auxCost: "Auxiliary Power",
    maintDepr: "Depreciation",
    setupTitle: "PMRX Cost Accounting",
    supportText: "Accurate cost analysis and ROI assessment for N2-methanol/Pure methanol vs high-efficiency RX gas solutions.",
    totalInvSummary: "Total Investment",
    comparison: "Comparison",
    startBtn: "Start Analysis",
    backBtn: "Back",
    model: "Model",
    quantity: "Qty",
    unitPrice: "Price",
    addItem: "Add Item",
    qty: "Qty",
    calcPrinciple: "Principle",
    viewDetail: "View Logic",
    summaryPriceTitle: "Meth / N2 / NG / Elec Price",
    sourceBtn: "Logic & Source Parameters",
    logicTitle: "Logic & Source Parameters",
    logicSub: "Core Engine Configuration",
    physConst: "Physical Constants",
    methVapor: "Meth Vapor Vol (m³/L)",
    methDensity: "Meth Density (kg/L)",
    modeCoeff: "Mode Control Coeff",
    nmCoeffTitle: "NM Calculation Logic",
    nmCoeffHint: "Gas = (Meth × VaporCoeff) + Nitrogen; Nitrogen = (Meth × VaporCoeff) × 4 / 6",
    pmCoeffTitle: "PM Ventilation Coeff",
    pmCoeffHint: "Gas = Meth × Vapor × Coeff",
    rxRatioTitle: "Rx Gas to Feed Ratio",
    crackElecTitle: "Cracking Power (kWh/L)",
    saveBtn: "Save & Update Version",
    deprCost: "Asset Depreciation",
    breakdownMethanol: "Methanol Cost",
    breakdownNitrogen: "N2/LN2 Cost",
    breakdownElec: "Electricity Cost",
    breakdownGas: "NG Cost",
    ln2Coeff: "LN2 Expansion Ratio"
  }
};

export const COLORS = {
  current: '#f59e0b',
  rx: '#22c55e',
  accent: '#3b82f6',
  background: '#f8fafc'
};